MusicSharing/Controllers/MusicController.cs
using log4net;
using Microsoft.AspNet.Identity;
using MusicSharing.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicSharing.Controllers
{
    public class MusicController : Controller
    {

        private static readonly ILog Log = LogManager.GetLogger(typeof(DefaultController));
        // GET: Music
        [Authorize]
        public ActionResult SearchMp3()
        {
            Log.Info("SearchMp3 accessed by " + User.Identity.GetUserName());

            dynamic materials = new System.Dynamic.ExpandoObject();
            DefaultConnection db = new DefaultConnection();
            foreach (var a in db.MusicFile.ToList())
            {
                copyMp3(a.musicFileUrl); 
            }
          
            return View(db.MusicFile.ToList());
        }


        public void copyMp3(string musicFileUrl)
        {


            //Get the full path of the file    
            //  var fullFilePath  = "\\\\mylab.local\\dfs\\data\\" + musicFileUrl;
            var fullFilePath = "D:\\Android\\"+ musicFileUrl;

            // Get the destination path

            var copyToPath = Server.MapPath("~/Content/music/"+ musicFileUrl);

            if (!System.IO.File.Exists(copyToPath)) {
                System.IO.File.Copy(fullFilePath, copyToPath);
            }
               

        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddMp3()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Delete()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
       [Authorize(Roles = "Admin")]
        public ActionResult AddMusic()
        {
            if (Request.Files.Count > 0)
            {
                try
                {
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {

                        HttpPostedFileBase file = files[i];
                        string fname;

                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            fname = file.FileName;
                        }

                        // string fname1 =  "\\\\mylab.local\\dfs\\data\\"+fname;
                        string fname1 = "D:\\Android\\" + fname;
                        //use threads

                        using (DefaultConnection db=new DefaultConnection()) {

                            DateTime dt =  DateTime.Now;
                            string id =  dt.ToString("yyyyMMddHHmmssffff");
                            var mid =  (from d in db.MusicFile orderby d.musicFileId descending select d.musicFileId).FirstOrDefault();
                            MusicFile music = new MusicFile
                            {
                                musicFileId = mid + 1,
                                musicFileName = fname,
                                songName = Request.Form["songTitle"],
                                singer = Request.Form["singer"],
                                musicFileUrl = fname,
                                size =  file.ContentLength.ToString(),
                                addedDate = DateTime.Now
                            };
                            db.MusicFile.Add(music);
                            db.SaveChanges();
                        }
                        file.SaveAs(fname1);
                    }
                    Log.Info("Add new mp3 file by" + User.Identity.GetUserName() + " - file.FileName");
                    return Json("File Uploaded Successfully!");
                    
                }
                catch (Exception ex)
                {
                    Log.Error("Error occored when Upload Music by "+ User.Identity.GetUserName(), ex);
                    return Json("Error occurred. Error details: " + ex.Message);
                    
                }
            }
            else
            {
                return Json("No files selected.");
            }
        }
    }
}

MusicSharing/Controllers/RoleController.cs
using log4net;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using MusicSharing.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicSharing.Controllers
{
    public class RoleController : Controller
    {
        private ApplicationDbContext context = new ApplicationDbContext();
        private static readonly ILog Log = LogManager.GetLogger(typeof(DefaultController));

        [Authorize(Roles = "Admin")]//Show Role List
        public ActionResult Index()
        {
           
            Log.Info(User.Identity.GetUserName()+ " Was access MusicSharing Index");
            return View(context.Roles.ToList());
        }

        [Authorize(Roles = "Admin")]//Load Create Role View
        public ActionResult Create()
        {


            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]//Save to DB new role
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                context.Roles.Add(new IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                context.SaveChanges();
                ViewBag.ResultMessage = "Role created successfully !";
                Log.Info(User.Identity.GetUserName() + " Was added new role call " + collection["RoleName"]);
                return View("Create");
            }
            catch
            {
                return View();
            }
        }
        //Delete Role
        public ActionResult Delete(string RoleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            Log.Info(User.Identity.GetUserName() + " Was Deleted role call " + RoleName);
            return RedirectToAction("Create");
        }


        //Load Edit role UI
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string roleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            Log.Info(User.Identity.GetUserName() + " Was  open Role Edit page");
            return View(thisRole);
        }


        //Edit the role
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IdentityRole role)
        {
            try
            {
                context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();
                Log.Info(User.Identity.GetUserName() + " Was Edited role call ");
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                Log.Error("Error occerd when Edit the Role", ex);
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult ManageUserRoles()
        {
            // prepopulat roles for the view dropdown
            Log.Info(User.Identity.GetUserName() + " Was  opened Role ManageUserRoles page");
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;
            return View();
        }

        [Authorize(Roles = "Admin")]//load mange user View
        public ActionResult ManageUsers()
        {
            // prepopulat roles for the view dropdown
            Log.Info(User.Identity.GetUserName() + " Was  opened Role ManageUsers page");
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>
            new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]//Assign role to User
        public ActionResult RoleAddToUser(string UserName, string RoleName)
        {

            Log.Info(User.Identity.GetUserName() + " Was  Assign role to User :" + UserName);
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context));
            manager.AddToRole(user.Id, RoleName);



            // prepopulat roles for the view dropdown
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;

            return View("ManageUsers");
        }

        //Retrive all the roles 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles(string UserName)
        {
            if (!string.IsNullOrWhiteSpace(UserName))
            {
                ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
                var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context));

                ViewBag.RolesForThisUser = manager.GetRoles(user.Id);
                Log.Info(User.Identity.GetUserName() + " Was  Checked the role of " + UserName);
                // prepopulat roles for the view dropdown
                var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
                ViewBag.Roles = list;
            }

            return View("ManageUsers");
        }

        //Delete Role from User
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser(string UserName, string RoleName)
        {
            var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context));

            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
           
            if (manager.IsInRole(user.Id, RoleName))
            {
                manager.RemoveFromRole(user.Id, RoleName);
                ViewBag.ResultMessage = "Role removed from this user successfully !";
                Log.Info(User.Identity.GetUserName() + " Was  remove role of " + RoleName + " form " + UserName);
            }
            else
            {
                ViewBag.ResultMessage = "This user doesn't belong to selected role.";
            }
            // prepopulat roles for the view dropdown
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;


            return View("ManageUsers");
        }

    }
}

MusicSharing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (this.User.IsInRole("Admin"))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Music
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("SearchMp3", "Music")">Search Mp3</a></li>
                                <li><a href="@Url.Action("AddMp3", "Music")">Add Mp3</a></li>
                            </ul>
                        </li>
                    }

                    @if (this.User.IsInRole("User"))
                    {
                        <li>@Html.ActionLink("Courses", "SearchMp3", "Music")</li>
                    }
                    @if (this.User.IsInRole("Admin"))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                User Management
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Register", "Account")">Register New User</a></li>
                                <li><a href="@Url.Action("Index", "Role")">Role List</a></li>
                                <li><a href="@Url.Action("Create", "Role")">Create Role</a></li>
                                <li><a href="@Url.Action("ManageUsers", "Role")">Role Management</a></li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>